### ISSUE TITLE
Implement mutation testing elements html report

### ISSUE THREAD

**Issue by Mobrockers** [MilleBo/Unima#2]
Hey! We also work on a C# mutation testing framework and we are happy to see more people interested in it :) Dropping by to say hello but also to point you in the direction of https://github.com/stryker-mutator/mutation-testing-elements

We created a generic json schema + corresponding html webcomponents that use this json to display a fancy report with the goal of creating a shared standard for reporting in mutation testing land. All you have to do is implement the schema as output and output the html including the json and you'll have a fancy html report basically for free :) You can check out https://github.com/stryker-mutator/stryker-net/blob/master/src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs and https://github.com/stryker-mutator/stryker-net/blob/417a2b78859425015c7a98ecb86ece301aa7b621/src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/Files/mutation-report.html for inspiration if you're interested.

**Comment by MilleBo** [comment]
Cool! Thanks I will take a look at it and see if I can implementer it to. A nice standard is always good to have.
