### ISSUE TITLE
Possible localization/UTF bug

### ISSUE THREAD

**Issue by 65001** [MilleBo/Unima#3]
On reddit my project was tested using your testing mutator suite [here](https://www.reddit.com/r/csharp/comments/bpgfob/looking_for_c_projects_with_good_test_coverage_to/env9zw7?utm_source=share&utm_medium=web2x). 

### Possible Localization Bug 
On that attached report, on the function `IsUnary` in the file `Data.cs` your program interpreted a part of that function have an equality check against `âˆ’` . The actual respective file linked [here](https://github.com/65001/AbMath/blob/master/AbMath/Calculator/Data.cs#L205) contains no such character or script which suggests there might be some kind of ASCII/UTF/localization bug in your code.

### Incorrect line numbers
The results report that is generated reports line numbers that do not line up with the actual line number in the `.cs` file.

**Comment by MilleBo** [comment]
The first one seems to be specific to the HTML generator because it looks okay if I check other reports, for example:

```
 {
			"Id": "0884b1ad-87e8-4c07-829a-3fadf14f22dc",
			"ProjectName": "AbMath",
			"FileName": "Data.cs",
			"Orginal": "value == \"−\" ",
			"Mutation": "value != \"−\"",
			"Survived": true,
			"CompilationResult": {
				"IsSuccess": true,
				"Errors": []
			},
			"TestsRunCount": 87,
			"FailedTests": [],
			"Location": {
				"Line": "@(116:62)",
				"Where": "IsUnary(M)"
			},
			"MutationName": "Proj: AbMath, File: Data.cs(IsUnary(M) - @(116:62))",
			"UnexpectedError": null,
			"Hash": "AA6D187146D30A8674010B1BB54726F7"
		}
```

But the line number is really weird so I will have to look. 

Thanks for reporting and I will try to fix both!

**Comment by MilleBo** [comment]
So I found/fixed the issues: 

**Possible Localization Bug**

Changed encoding when writing the html template so this should hopefully fix the issue. 

**Incorrect line numbers**

You have two different Data.cs files so make sure that you check in the correct one. At first I thought it was a but but then I found the second file and all the lines matched fine. So I don't think this is an issue.
