### ISSUE TITLE
Respect ExcludeFromCodeCoverage attribute

### ISSUE THREAD

**Issue by jpdillingham** [MilleBo/Unima#6]
As with other testing frameworks, exclude any class or structure marked with [ExcludeFromCodeCoverage](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=netframework-4.8) from analysis.

**Comment by MilleBo** [comment]
Seems like a good idea, I will try to add that in the next couple of days.

**Comment by MilleBo** [comment]
We now support this attribute (with release 1.1.0).  So we will not mutate code in classes, methods or properties that have this attribute.
